# Generated by Django 6.0.5 on 2026-05-31 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workerportfolio',
            name='image',
            field=models.TextField(),
        ),
    ]
