# Generated by Django 6.0.5 on 2026-06-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_latitude_alter_user_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cell',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='village',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
