# Generated by Django 6.0.5 on 2026-06-07 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_professional_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='evidence_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='jobactivity',
            name='event_type',
            field=models.CharField(choices=[('posted', 'Job Posted'), ('application_received', 'Application Received'), ('worker_hired', 'Worker Hired'), ('started', 'Work Started'), ('completion_submitted', 'Completion Proof Submitted'), ('completed', 'Job Completed'), ('payment_held', 'Payment Held'), ('payment_released', 'Payment Released'), ('dispute_opened', 'Dispute Opened'), ('dispute_resolved', 'Dispute Resolved'), ('reviewed', 'Review Submitted'), ('cancelled', 'Job Cancelled')], max_length=30),
        ),
        migrations.CreateModel(
            name='MoMoTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('collection', 'Collection'), ('disbursement', 'Disbursement')], max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phone', models.CharField(max_length=20)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('external_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='momo_transactions', to='jobs.job')),
            ],
        ),
    ]
