# Generated by Django 6.0.5 on 2026-06-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_report_evidence_urls_alter_jobactivity_event_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='latitude',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='longitude',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
    ]
