# Generated by Django 6.0.5 on 2026-06-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_job_latitude_alter_job_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='cell',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='village',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
