# Generated by Django 6.0.5 on 2026-06-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('job_posted', 'Job Posted Nearby'), ('job_accepted', 'Job Accepted'), ('job_completed', 'Job Completed'), ('new_application', 'New Application'), ('application_submitted', 'Application Submitted'), ('application_rejected', 'Application Rejected'), ('new_message', 'New Message'), ('emergency_job', 'Emergency Job Nearby'), ('review_received', 'Review Received'), ('verification_approved', 'Verification Approved'), ('verification_rejected', 'Verification Rejected')], max_length=30),
        ),
    ]
